version: '3.4'

services:
  altamira:
    image: ${DOCKER_REGISTRY-}altamira
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sql_server
      - redis   

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '5002'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  sql_server:
    build:
      context: .
      dockerfile: sql/sql.Dockerfile
    ports:
      - '1440:1433'
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    