version: '3.4'

services:
  elasticsearch:
    image: elasticsearch:7.14.0
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.14.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    depends_on:
      - elasticsearch

  altamira:
    image: ${DOCKER_REGISTRY-}altamira
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sql_server
      - redis   
      - kibana
  
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  sql_server:
    build:
      context: .
      dockerfile: sql/sql.Dockerfile
    ports:
      - '1440:1433'
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"

